---
# tasks file for roles/nomad
- name: Generate nomad config.
  ansible.builtin.template:
    src: "{{ role_path }}/templates/nomad.hcl.j2"
    dest: "/etc/nomad.d/nomad.hcl"
    owner: root
    group: root
    mode: '0600'