---
- name: Install and configure nomad.
  hosts: localhost
  roles: 
    - role: installation   
    - role: server-client   
    - role: service
  handlers:
    - include_tasks: roles/service/handlers/main.yaml