---
- name: Install and configure nomad.
  hosts: localhost
  tasks:
    - name: Import Hashicorp GPG key.
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
