---
- name: Install and configure nomad.
  hosts: localhost
  roles: 
    - role: installation
      tags: [ always ]

    - role: nomad
      tags: [ always ]

    - role: server
      tags: [ server ]
    
    - role: client
      tags: [ client ]
    
    - role: service
      tags: [ always ]