---
# tasks file for roles/ingress
- name: Force nomad service handler to run.
  ansible.builtin.meta: flush_handlers
# - name: Create ingress nginx job.
#   community.general.nomad_job:
#     host: localhost
#     state: present
#     content: "{{ lookup('ansible.builtin.file', '{{ role_path }}/files/nginx.hcl') }}"
#     timeout: 120
#     use_ssl: false
- name: hola
  ansible.builtin.debug: msg="hola"
