---
# tasks file for roles/ingress
- meta: flush_handlers
- name: Create ingress Traefik.
  community.general.nomad_job:
    host: localhost
    state: present
    content: "{{ lookup('ansible.builtin.file', '{{ role_path }}/files/traefik.hcl') }}"
    timeout: 120
    use_ssl: false
- name: Create nginx job to expose API to traefik.
  community.general.nomad_job:
    host: localhost
    state: present
    content: "{{ lookup('ansible.builtin.file', '{{ role_path }}/files/nginx.hcl') }}"
    timeout: 120
    use_ssl: false