---
# tasks file for ./roles/service
- name: Copy nomad service.
  copy:
    src: "{{ role_path }}/files/nomad.service"
    dest: "/etc/systemd/system"
    owner: root
    group: root
  notify:
    - Start nomad
- name: Copy nomad config.
  copy:
    src: "{{ role_path }}/files/config.hcl"
    dest: "/etc/nomad.d/config"
    owner: root
    group: root
  notify:
    - Start nomad