---
# tasks file for roles/scheduler
- name: Copy update service file to server
  copy:
    src: "{{ role_path }}/files/update/update_packages.service"
    dest: "/etc/systemd/system"
    owner: root
    group: root
  notify:
    - Start update_packages
  tags: apache nginx

- name: Copy update timer file to server
  copy:
    src: "{{ role_path }}/files/update/update_packages.timer"
    dest: "/etc/systemd/system"
    owner: root
    group: root
  notify:
    - Start update_packages
  tags: apache nginx

- name: Copy binary to apache server
  copy:
    src: "{{ role_path }}/files/update/apache/update_packages.sh"
    dest: "/root"
    mode: 0755
    owner: root
    group: root
  notify:
    - Start update_packages
  tags: apache

- name: Copy binary to nginx server
  copy:
    src: "{{ role_path }}/files/update/nginx/update_packages.sh"
    dest: "/root"
    mode: 0755
    owner: root
    group: root
  notify:
    - Start update_packages
  tags: nginx