---
# tasks file for roles/apache
- name: Create default containers
  community.docker.docker_container:
    name: "apache"
    image: "php:7.4-apache"
    state: started
    ports:
      - "80:80"
    volumes:
      - "/volumes/apache/www:/var/www/html/"
      
- name: Generate index.html
  ansible.builtin.template:
    src: "{{ role_path }}/templates/index.html.j2"
    dest: "/volumes/apache/www/index.html"