---
# tasks file for roles/apache
- name: Create directory for volume.
  ansible.builtin.file:
    path: /volumes/nginx/conf.d
    state: directory

- name: Generate default.conf
  ansible.builtin.template:
    src: "{{ role_path }}/templates/default.conf.j2"
    dest: "/volumes/nginx/conf.d/default.conf"

- name: Create nginx container
  community.docker.docker_container:
    name: "nginx"
    image: "nginx"
    state: started
    ports:
      - "80:80"
    volumes:
      - "/volumes/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"