# tasks installation file for roles/common
- name: Install specified python requirements .
  ansible.builtin.pip:
    requirements: "{{ role_path }}/files/installation/requirements.txt"
- name: Install docker with apt.
  become: true
  ansible.builtin.apt:
    name: docker.io==20.10.16-0ubuntu1
    state: present
  register: docker
- name: Print docker
  debug:
    msg: "{{ docker }}"