---
# tasks file for roles/server-client
- name: Generate nomad config.
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config.hcl.j2"
    dest: "/etc/nomad.d/config.hcl"
    owner: root
    group: root